-- p87 ~ p90 , 인덱스를 Range Scan 할 수 없는 이유 
CREATE INDEX e_x01 ON emp(deptno);
CREATE INDEX e_x02 ON emp(deptno, job);
CREATE INDEX e_x03 ON emp(job);

EXPLAIN PLAN FOR 
SELECT /*+ index(E e_x01) */ * FROM EMP E WHERE E.DEPTNO BETWEEN 10 AND 20;

-- INDEX RANGE SCAN (e_x02)
explain plan FOR 
SELECT E.JOB FROM EMP E WHERE E.JOB = 'MANAGER';

-- INDEX FULL SCAN (e_x03)
explain plan FOR 
SELECT E.JOB FROM EMP E WHERE substr(E.JOB, 1, 2) = 'A';

-- INDEX RANGE SCAN (e_x01)
EXPLAIN PLAN FOR 
SELECT E.DEPTNO FROM EMP E WHERE E.DEPTNO = 20;

-- 책에는 INDEX RANGE SCAN 안된다는데 e_x01 인덱스 사용되서 INDEX RANGE SCAN이 됨..... 
EXPLAIN PLAN FOR 
SELECT E.DEPTNO FROM EMP E WHERE NVL(E.DEPTNO, 0) < 20;

-- INDEX FULL SCAN (e_x03)
EXPLAIN PLAN FOR 
SELECT E.JOB FROM EMP E WHERE E.JOB LIKE '%NAG%';

-- INDEX FULL SCAN (e_x02)
EXPLAIN PLAN FOR 
SELECT E.JOB, E.DEPTNO FROM EMP E WHERE (E.DEPTNO = 20 OR E.JOB = 'MANAGER');

-- OR Expansion
EXPLAIN PLAN FOR
SELECT JOB, DEPTNO 
FROM EMP 
WHERE DEPTNO = 20
UNION ALL
SELECT JOB, DEPTNO 
FROM EMP
WHERE JOB = 'MANAGER'
AND (DEPTNO != 20 OR DEPTNO IS NULL);

-- use concat
EXPLAIN PLAN FOR
SELECT /*+ use_concat */ E.JOB, E.DEPTNO FROM EMP E
WHERE (E.DEPTNO = 20 OR E.JOB = 'MANAGER');

-- INLIST ITERATOR (RANGE SCAN, e_x01)
EXPLAIN PLAN FOR
SELECT DEPTNO 
FROM EMP 
WHERE DEPTNO IN (10, 20);

-- UNION ALL 방식 (RANGE SCAN + RANGE SCAN)
EXPLAIN PLAN FOR
SELECT DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION ALL
SELECT DEPTNO
FROM EMP
WHERE DEPTNO = 20;

-- 실행계획 확인 
SELECT * FROM TABLE(dbms_xplan.display(NULL, NULL, 'ALL'));


-- p95, 인덱스를 이용한 소트 연산 생략
EXPLAIN PLAN FOR
SELECT /*+ index(E e_x02) */ E.DEPTNO FROM EMP E 
WHERE E.DEPTNO = 10;

EXPLAIN PLAN FOR
SELECT E.DEPTNO FROM EMP E
WHERE E.DEPTNO = 10
ORDER BY E.JOB;

EXPLAIN PLAN FOR
SELECT /*+ index(E e_x02) */ E.DEPTNO FROM EMP E
WHERE E.DEPTNO = 10
ORDER BY E.ENAME;

EXPLAIN PLAN FOR
SELECT E.DEPTNO FROM EMP E
WHERE E.DEPTNO = 10
ORDER BY E.JOB DESC;

-- 실행계획 확인
SELECT * FROM TABLE(dbms_xplan.display(NULL, NULL, 'ALL'));


-- p97, order by 절에서 컬럼 가공
EXPLAIN PLAN FOR
SELECT * 
FROM EMP E
WHERE E.DEPTNO = 10
ORDER BY E.DEPTNO, E.JOB;

EXPLAIN PLAN FOR
SELECT * 
FROM EMP E
WHERE E.DEPTNO = 10
ORDER BY E.DEPTNO || E.JOB;

-- 실행계획 확인
SELECT * FROM TABLE(dbms_xplan.display(NULL, NULL, 'ALL'));


-- p100, SELECT-LIST 에서 컬럼 가공 
EXPLAIN PLAN FOR
SELECT MAX(E.JOB)
FROM EMP E
WHERE E.DEPTNO = 10;

EXPLAIN PLAN FOR
SELECT MIN(E.JOB)
FROM EMP E
WHERE E.DEPTNO = 10;

EXPLAIN PLAN FOR
SELECT MIN(E.EMPNO)
FROM EMP E
WHERE E.DEPTNO = 10;


-- P104, 자동형변환
EXPLAIN PLAN FOR
SELECT E.DEPTNO 
FROM EMP E
WHERE E.DEPTNO = 10;

-- filter(TO_CHAR("E"."DEPTNO")='10')
-- filter(TO_CHAR("E"."DEPTNO") LIKE '10%')
EXPLAIN PLAN FOR
SELECT E.DEPTNO 
FROM EMP E
WHERE E.DEPTNO LIKE '10%';

EXPLAIN PLAN FOR
SELECT E.DEPTNO 
FROM EMP E
WHERE E.DEPTNO LIKE NULL || '%';

-- 실행계획 확인
SELECT * FROM TABLE(dbms_xplan.display(NULL, NULL, 'ALL'));

