-- 조인 
-- ======================================================
SELECT A.ENAME AS 사원명, A.JOB AS 급여, A.SAL AS 급여, B.GRADE AS 급여등급 
FROM EMP A, SALGRADE B
WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL;

SELECT A.*, B.DNAME 
FROM EMP A, DEPT B 
WHERE B.DEPTNO(+) = A.DEPTNO; 

SELECT A.*, B.DNAME 
FROM EMP A, DEPT B 
WHERE B.DEPTNO = A.DEPTNO(+); 

SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME 
FROM EMP A, DEPT B
WHERE B.DEPTNO = A.DEPTNO;

SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME
FROM EMP A INNER JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME
FROM EMP A JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

SELECT A.EMPNO, A.ENAME, DEPTNO, B.DNAME 
FROM EMP A NATURAL JOIN DEPT B;

SELECT * 
FROM EMP A NATURAL JOIN DEPT B;

SELECT *
FROM EMP A INNER JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT;
-- MsSQL : SELECT * INTO DEPT_TEMP FROM DEPT;

UPDATE DEPT_TEMP
SET DNAME = 'CONSULTING'
WHERE DNAME = 'RESEARCH';

UPDATE DEPT_TEMP
SET DNAME = 'MARKETING'
WHERE DNAME = 'SALES';

SELECT * FROM DEPT_TEMP;

SELECT *
FROM DEPT A NATURAL INNER JOIN DEPT_TEMP B;

SELECT *
FROM DEPT A JOIN DEPT_TEMP B
ON B.DEPTNO = A.DEPTNO 
AND B.DNAME = A.DNAME 
AND B.LOC = A.LOC;

SELECT *
FROM DEPT A JOIN DEPT_TEMP B 
USING (DEPTNO);

SELECT DEPTNO, A.DNAME, A.LOC, B.DNAME, B.LOC
FROM DEPT A JOIN DEPT_TEMP B 
USING (DEPTNO);

SELECT * 
FROM DEPT A JOIN DEPT_TEMP B  
USING (DNAME);

SELECT *
FROM DEPT A JOIN DEPT_TEMP B 
USING (LOC, DEPTNO);

SELECT * 
FROM DEPT A JOIN DEPT_TEMP B
USING (DEPTNO, DNAME);

SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME
FROM EMP A JOIN DEPT B 
ON (B.DEPTNO = A.DEPTNO);

SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME 
FROM EMP A JOIN DEPT B
ON B.DEPTNO = A.DEPTNO 
WHERE B.DEPTNO = 30;

SELECT A.ENAME, A.MGR, A.DEPTNO, B.DNAME 
FROM EMP A JOIN DEPT B 
ON B.DEPTNO = A.DEPTNO 
AND A.MGR = 7698;

SELECT A.EMPNO, A.DEPTNO, B.DNAME, C.DNAME AS NEW_DNAME
FROM EMP A JOIN DEPT B 
ON B.DEPTNO = A.DEPTNO JOIN DEPT_TEMP C 
ON C.DEPTNO = B.DEPTNO;

SELECT A.EMPNO, A.DEPTNO, B.DNAME, C.DNAME AS NEW_DNAME
FROM EMP A, DEPT B, DEPT_TEMP C 
WHERE B.DEPTNO = A.DEPTNO 
AND C.DEPTNO = B.DEPTNO;

SELECT A.ENAME, B.DNAME 
FROM EMP A CROSS JOIN DEPT B 
ORDER BY A.ENAME;

SELECT A.ENAME, B.DNAME
FROM EMP A CROSS JOIN DEPT B 
WHERE B.DEPTNO = A.DEPTNO;

SELECT A.ENAME, B.DEPTNO, B.DNAME, B.LOC
-- FROM EMP A RIGHT OUTER JOIN DEPT B 
FROM EMP A RIGHT JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

UPDATE DEPT_TEMP 
SET DEPTNO = DEPTNO + 20;

SELECT * FROM DEPT_TEMP;

SELECT *
-- FROM DEPT A FULL OUTER JOIN DEPT_TEMP B 
FROM DEPT A FULL JOIN DEPT_TEMP B
ON B.DEPTNO = A.DEPTNO;