-- 집합 연산자 
-- ================================================== 

SELECT PLAYER_NAME, BACK_NO 
FROM PLAYER
WHERE TEAM_ID = 'K02'
UNION 
SELECT PLAYER_NAME, BACK_NO 
FROM PLAYER
WHERE TEAM_ID = 'K07'
ORDER BY 1;

SELECT TEAM_ID, PLAYER_NAME, POSITION, BACK_NO, HEIGHT  
FROM PLAYER
WHERE TEAM_ID = 'K02'
UNION 
SELECT TEAM_ID, PLAYER_NAME, POSITION, BACK_NO, HEIGHT  
FROM PLAYER
WHERE TEAM_ID = 'K07';

SELECT DISTINCT TEAM_ID, PLAYER_NAME, POSITION, BACK_NO, HEIGHT 
FROM PLAYER
WHERE TEAM_ID = 'K02'
OR TEAM_ID = 'K07';

SELECT DISTINCT TEAM_ID, PLAYER_NAME, POSITION, BACK_NO, HEIGHT 
FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07');

SELECT 팀코드, 선수명, 포지션, 백넘버, 키 
FROM (
	SELECT TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명
		 , POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
	FROM PLAYER 
	WHERE TEAM_ID = 'K02'
	UNION ALL
	SELECT TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명
		 , POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
	FROM PLAYER 
	WHERE POSITION = 'GK'
)
GROUP BY 팀코드, 선수명, 포지션, 백넘버, 키 
HAVING COUNT(*) > 1;

SELECT 'P' AS 구분코드, POSITION AS 포지션, ROUND(AVG(HEIGHT),3) AS 평균키 
FROM PLAYER
GROUP BY "POSITION"
UNION ALL 
SELECT 'T' AS 구분코드, TEAM_ID AS 팀명, ROUND(AVG(HEIGHT),3) AS 평균키 
FROM PLAYER
GROUP BY TEAM_ID 
ORDER BY 1;

SELECT TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명
	, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER 
WHERE TEAM_ID = 'K08'
MINUS
SELECT TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명
	 , POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER 
WHERE POSITION = 'ST';

SELECT DISTINCT 
	   TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명
	 , POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER A 
WHERE A.TEAM_ID = 'K08'
AND NOT EXISTS (SELECT 1 
				FROM PLAYER X 
				WHERE X.PLAYER_ID = A.PLAYER_ID
				AND X."POSITION" = 'ST');

SELECT DISTINCT 
	   TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명
	 , POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER A 
WHERE A.TEAM_ID = 'K08'
AND PLAYER_ID NOT IN (SELECT X.PLAYER_ID 
					  FROM PLAYER X 
					  WHERE X."POSITION" = 'ST')
ORDER BY 1,2,3,4,5;

SELECT DISTINCT 
	   TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명
	 , POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER A 
WHERE A.TEAM_ID = 'K08'
AND "POSITION" <> 'ST'
ORDER BY 1,2,3,4,5;

SELECT TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명
	, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER 
WHERE TEAM_ID = 'K08'
INTERSECT
SELECT TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명
	 , POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER 
WHERE POSITION = 'ST'
AND BACK_NO = 10;